[package]
name = "rust_cache"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.19.0"
lru = "0.12.3"
libc = "0.2"
windows-sys = { version = "0.59.0", features = [
    "Win32_System_Memory",
    "Win32_System_Threading"
] }